FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

ARG AWS_DATASOURCE_CONFIG
ENV AWS_DATASOURCE_CONFIG=${AWS_DATASOURCE_CONFIG}
ARG AWS_DATASOURCE_PASSPHRASE
ENV AWS_DATASOURCE_PASSPHRASE=${AWS_DATASOURCE_PASSPHRASE}

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 80
CMD [ "npm", "run", "local-serve" ]